name: Update Resume on Website

on:
  push:
    branches:
      - main # Replace with your default branch

jobs:
  update-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Installing ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
      - name: Refresh resume
        run: |
          ssh -o StrictHostKeyChecking=no billy@${{ secrets.DROPLET_IP }} << 'EOF'
            cd ~/resume
            git pull
          EOF

